### ISSUE TITLE
promethion models

### ISSUE THREAD

**Issue by rrazaghi** [nanoporetech/rerio#11]
Hi again Marcus,

Is it safe to say that there isn't a rerio model for m6A calling on prom? I accidentally tried the minion/grid model on a prom run and I'm observing a much higher methylation percentage genome wide compared to the same sample ran on gridion. 
If this is true, is there a timeline for prom compatibility?

Thanks!

**Comment by davidnewman02** [comment]
6mA methylation calling is now supported in Dorado
