### ISSUE TITLE
new models

### ISSUE THREAD

**Issue by QGouil** [nanoporetech/rerio#13]
Hi Marcus,

the download.py script doesn't like the new models, for example
`rerio/download_model.py rerio/basecall_models/res_dna_r941_prom_modbases_5mC_v001`

> #Error for res_dna_r941_prom_modbases_5mC_v001 (not a gzip file)

I tried going to the url and downloading the .cfg and .jsn files, but couldn't run megalodon.
The .cfg file contains:
># Basecalling.
>model_file                          = native_model.jsn

instead of the expected res_dna_r941_prom_modbases_5mC_v001.jsn. 
Even tweaking this doesn't allow megalodon to run:
>        ERROR: No default modified base calibration file found for guppy config: >res_dna_r941_prom_modbases_5mC_v001_tweaked.cfg

Probably something wrong in the upload of the new models?
Cheers,
Quentin

**Comment by marcus1487** [comment]
This was a combination of two bugs (one in Rerio and one in Megalodon). Thank you for the detailed report! The rerio models should be corrected now. This should just require the downloading of the models again to retrieve the fixed config file. The Megalodon bug has also been fixed with a new release that was just pushed (will take about a day to update on conda). Please re-open if this issue persists.

**Comment by QGouil** [comment]
Thanks Marcus, giving it a try now. I forgot to mention one other bug. The .cfg also mentions
`# Adapter scaling

as_model_file                      = adapter_scaling_dna_r9.4.1_prom.jsn`

but this adapter scaling file doesn't seem to be downloaded along the cfg and main jsn. Is it important? Megalodon seems happy to run with these lines commented out.
Cheers!

**Comment by marcus1487** [comment]
The model will likely work well without the adapter scaling model. Thank you for this report as well. I will fix this shortly.

**Comment by marcus1487** [comment]
I should also note that the adapter scaling model file can be copied from the guppy data directory to the rerio basecalling models directory to fix this issue.

**Comment by marcus1487** [comment]
New models have been uploaded with the adapter scaling models attached. So the download script should work as described in the README now or the new 5mC models. Again please report if any issues are encountered.
