### ISSUE TITLE
Model details

### ISSUE THREAD

**Issue by PanZiwei** [nanoporetech/rerio#14]
Hi Marcus,
I found that you recently uploaded the model named 'res_dna_r941_min_modbases_5mC_5hmC_CpG_v001' and 'res_dna_r941_min_modbases_5mC_5hmC_v001' under [rerio/basecall_models/](https://github.com/nanoporetech/rerio/tree/master/basecall_models), can you explain more about these two models? What are the differences between the two models? What dataset do you use to train and get the two models?

For 'res_dna_r941_min_modbases_5mC_5hmC_v001.cfg', you mentioned in the README.rst file that "It is 5hmC & 5mC in all context", does that mean that all cytosines in the model are modified? Do we know the modification state for a specific C?

Thank you so much for your help!

**Comment by marcus1487** [comment]
The `res_dna_r941_min_modbases_5mC_5hmC_CpG_v001` model has been deprecated in favor of the updated `res_dna_r941_min_modbases_5mC_5hmC_v001` model. The main difference is updates to the training pipeline including parameter tuning and inclusion of software bug fixes in Taiyaki and Megalodon. 

The CpG performance between the models is similar, but the newer `res_dna_r941_min_modbases_5mC_5hmC_v001` model should perform better in other cytosine contexts. This is the reason that the `res_dna_r941_min_modbases_5mC_5hmC_CpG_v001` model is not listed in the README table (but is still available in the repository for people still interested; models may be removed at a future date, but will likely remain in the repository history). 

Both final models were trained mostly from native human data as well as some synthetic proprietary samples.

Note that this model is considered quite preliminary and we hope to see great improvement in this model in the near future. One point to emphasis with this model is that the 5hmC calls are not very confident. For this reason, when processing with Megalodon it is recommended to use the following setting `--mod-binary-threshold 0`. This will force Megalodon to make a call at each cytosine (normally unconfident calls are ignored, which could be quite a high fraction of calls with the 5hmC models).

For the all-context bit, this refers to the reference sequence contexts in which the model was trained. Previous model were trained only to detect 5mC and 5hmC in CG sequence contexts. These models had some power to detect modified bases outside this sequence context, but the performance was drastically lowered. The newer models have been trained specifically to detect modified bases in all sequence contexts.

I hope this helps and please respond with more specific questions should they arise.
