### ISSUE TITLE
Support for Bonito research models 

### ISSUE THREAD

**Issue by tungufoss** [nanoporetech/rerio#15]
I saw on the release notes for Guppy v4.4.0 that there is preliminary support for bonito research models and the guppy compatible model would be available in the rerio repo. Which model exactly is it?

**Comment by cjw85** [comment]
Hi Helga!

From my brief check I can't obviously tell which model file you should use either (or indeed if its present). I will follow this up internally.

**Comment by cjw85** [comment]
@tungufoss,

@iiSeymour will follow up here, contrary to the release note a model file isn't yet present in the repository.

**Comment by iiSeymour** [comment]
Hey @tungufoss 

The following bonito models are now available to run with guppy 4.4.0+ 

 - basecall_models/res_dna_r103_min_crf_v030
 - basecall_models/res_dna_r941_min_crf_v031
 
Chris.

**Comment by tungufoss** [comment]
Thanks @iiSeymour 
We'll start benchmarking the model on our in-house data now.

Helga

**Comment by tungufoss** [comment]
FYI, we're noticing errors using this model (using guppy v4.4.1). I've contacted Forrest regarding sending over problematic fast5s.

**Comment by iiSeymour** [comment]
Thanks @tungufoss - we have this fixed in 4.4.2 https://community.nanoporetech.com/posts/guppy-v4-4-2-patch-release
