### ISSUE TITLE
fastq output format errors with guppy 4.4.1

### ISSUE THREAD

**Issue by RichardCorbett** [nanoporetech/rerio#17]
Hi folks,

I am using guppy 4.4.1 with the latest rerio config files and am getting errors suggesting a problem with file formats.

My command:
` /opt/ont-guppy_4.4.1/bin/guppy_basecaller     --input_path fast5      --save_path guppy_4_4_1_PAE96295        -d bin/rerio/basecall_models     -c res_dna_r941_min_crf_v031.cfg       --compress_fastq        --qscore_filtering      --recursive     --device "cuda:0 cuda:1 cuda:2 cuda:3"  --disable_pings`

Output:
```
Command exit status:
  139

Command output:
  ONT Guppy basecalling software version 4.4.1+1c81d62
  config file:        /home/rcorbett/bin/rerio/basecall_models/res_dna_r941_min_crf_v031.cfg
  model file:         /home/rcorbett/bin/rerio/basecall_models/res_dna_r941_min_crf_v031.jsn
  input path:         fast5
  save path:          guppy_4_4_1_PAE96295
  chunk size:         720
  chunks per runner:  320
  minimum qscore:     7
  records per file:   4000
  fastq compression:  ON
  num basecallers:    4
  gpu device:         cuda:0 cuda:1 cuda:2 cuda:3
  kernel path:        
  runners per device: 8
  Found 3915 fast5 files to process.
  Init time: 21294 ms
  
  0%   10   20   30   40   50   60   70   80   90   100%
  |----|----|----|----|----|----|----|----|----|----|
  ***************************************************

Command error:
  [guppy/error] pipeline::ThreadedNode::worker_function: Exception thrown in dataHandlerNode worker thread: Sequence contained an unexpected character '�' at position 621
  .command.sh: line 2: 641593 Segmentation fault      (core dumped) /opt/ont-guppy_4.4.1/bin/guppy_basecaller --input_path fast5 --save_path guppy_4_4_1_PAE96295 -d /home/rcorbett/bin/rerio/basecall_models -c res_dna_r941_min_crf_v031.cfg --compress_fastq --qscore_filtering --recursive --device "cuda:0 cuda:1 cuda:2 cuda:3" --disable_pings
```

I have tried this on multiple samples and each time I get an error similar to what I have above.  Do you have any suggestions about how to get around this?

**Comment by tmassingham-ont** [comment]
Hello.  We think the issue is Guppy having problems with particular reads, rather than an issue with the model itself.  
This issue only affects the new "CRF" models and a fix to Guppy with be released shortly, sorry for the inconvenience.

**Comment by fbrennen** [comment]
Hi @RichardCorbett -- do you have a fast5 file that replicates the issue that we could have?

**Comment by RichardCorbett** [comment]
I wish I could.  I think I'm playing whack-a-mole here.   I had a set of fast5 in which there was at least 1 read that caused the crash, but now when I re-run I can't reproduce it.

**Comment by RichardCorbett** [comment]
Found what looks like a memory issue with a different sample.   I'm trying to reproduce the error, but it may be a few hours before I get to the same point.   If I try and pull out the fast5 files that would likely have been processed at the time of the crash (by matching ids in the output fastqs and the sequencing_summary.txt file) I can't get it to crash again.

Here is the output, with the error:
```
/opt/ont-guppy_4.4.1/bin/guppy_basecaller  --input_path fast5 --save_path guppy_4_4_1_PAE96295 -d /home/rcorbett/bin/rerio/basecall_models -c res_dna_r941_min_crf_v031.cfg --compress_fastq --qscore_filtering --recursive --device "cuda:4 cuda:5 cuda:6 cuda:7" --disable_pings
ONT Guppy basecalling software version 4.4.1+1c81d62
config file:        /home/rcorbett/bin/rerio/basecall_models/res_dna_r941_min_crf_v031.cfg
model file:         /home/rcorbett/bin/rerio/basecall_models/res_dna_r941_min_crf_v031.jsn
input path:         fast5
save path:          guppy_4_4_1_PAE96295
chunk size:         720
chunks per runner:  320
minimum qscore:     7
records per file:   4000
fastq compression:  ON
num basecallers:    4
gpu device:         cuda:4 cuda:5 cuda:6 cuda:7
kernel path:        
runners per device: 8
Found 3915 fast5 files to process.
Init time: 12735 ms

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***[guppy/error] pipeline::ThreadedNode::worker_function: Exception thrown in dataHandlerNode worker thread: Sequence contained an unexpected character '?' at position 329
************************************************
malloc(): unsorted double linked list corrupted
Aborted (core dumped)
```

**Comment by RichardCorbett** [comment]
Confirmed that the error isn't deterministic by running the same command as above, but got a different error:

```
/opt/ont-guppy_4.4.1/bin/guppy_basecaller  --input_path fast5 --save_path guppy_4_4_1_PAE96295 -d /home/rcorbett/bin/rerio/basecall_models -c res_dna_r941_min_crf_v031.cfg --compress_fastq --qscore_filtering --recursive --device "cuda:4 cuda:5 cuda:6 cuda:7" --disable_pings
ONT Guppy basecalling software version 4.4.1+1c81d62
config file:        /home/rcorbett/bin/rerio/basecall_models/res_dna_r941_min_crf_v031.cfg
model file:         /home/rcorbett/bin/rerio/basecall_models/res_dna_r941_min_crf_v031.jsn
input path:         fast5
save path:          guppy_4_4_1_PAE96295
chunk size:         720
chunks per runner:  320
minimum qscore:     7
records per file:   4000
fastq compression:  ON
num basecallers:    4
gpu device:         cuda:4 cuda:5 cuda:6 cuda:7
kernel path:        
runners per device: 8
Found 3915 fast5 files to process.
Init time: 12738 ms

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
**[guppy/error] pipeline::ThreadedNode::worker_function: Exception thrown in dataHandlerNode worker thread: Sequence contained an unexpected character 'M' at position 0
*************************************************
[guppy/error] main: The pipeline has shut down prematurely due to an error condition.
[guppy/warning] main: An error has occurred. Aborting.
```

**Comment by fbrennen** [comment]
Thanks very much for the additional investigation. If you can narrow this down to a file that even occasionally reproduces the error that would still be very helpful.

**Comment by RichardCorbett** [comment]
Understood.  Is it correct that looking at the last reported read in the sequencing_summary.txt file would be adjacent to a read on which guppy failed?   Is there a better place to look in the logs that are created, or perhaps just looking at the last fastq file that is created that would give the best indicator of which fast5 file was being processed during the crash?

**Comment by fbrennen** [comment]
Looking at the basecaller log file is the way to go (they'll be in your output folder with everything else). Each read will have an entry from when it was sent to the basecaller and and entry from when it was returned, and you can use that to get a rough idea of which files had reads being basecalled at a particular time (they'll be the ones that were sent to the basecaller but haven't come back yet).

**Comment by RichardCorbett** [comment]
Sorry but I can't seem to lock it down to a file.    For example, I have a flowcell for which guppy 4.4.1 crashes after 40 minutes with the error above (or similar).  When I start it with `--resume` it runs again for another 30 minutes eventually crashing at a different fast5 file, but having completed the one that was processing when the first crash occurred.  Each time I re-start with `--resume`.  I can process a further few hundred fast5s and then it crashes.

**Comment by charles-plessy** [comment]
Same here, after a couple of `--resume` the basecall was eventually declared complete by _Guppy_. Example error messages:

`[guppy/error] pipeline::ThreadedNode::worker_function: Exception thrown in dataHandlerNode worker thread: Sequence contained an unexpected character '�' at position 961`

`[guppy/error] pipeline::ThreadedNode::worker_function: Exception thrown in dataHandlerNode worker thread: Sequence contained an unexpected character '>' at position 6`

`[guppy/error] pipeline::ThreadedNode::worker_function: Exception thrown in dataHandlerNode worker thread: Sequence contained an unexpected character '>' at position 0`

`[guppy/error] pipeline::ThreadedNode::worker_function: Exception thrown in dataHandlerNode worker thread: Sequence contained an unexpected character '�' at position 6`

**Comment by fbrennen** [comment]
Hi @RichardCorbett @charles-plessy -- thanks for the update. We're trying to replicate this internally. Could you tell us what GPUs you're using, and what driver and CUDA versions you have installed?

**Comment by RichardCorbett** [comment]
Hi @fbrennen ,
We are using CUDA 11 on a GeForce RTX 3090.
```
nvidia-smi
Wed Jan 20 07:48:49 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.45.01    Driver Version: 455.45.01    CUDA Version: 11.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 3090    Off  | 00000000:1A:00.0 Off |                  N/A |
| 32%   46C    P0   111W / 350W |      0MiB / 24268MiB |      0%      Default |
|                               |                      |                  N/A |
...
```

**Comment by charles-plessy** [comment]
```
$ srun -p gpu --gres gpu:1 nvidia-smi
Thu Jan 21 12:07:07 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.32.00    Driver Version: 455.32.00    CUDA Version: 11.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-SXM2...  On   | 00000000:07:00.0 Off |                    0 |
| N/A   32C    P0    36W / 300W |      0MiB / 16280MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by fbrennen** [comment]
Thanks both. We'll let you know as soon as we have an update.

**Comment by drfultz** [comment]
Same error here, also occurring at seemingly random times.  Guppy 4.4.1 w/ bonito CRF model.  Sometimes guppy will run for 30 minutes then error.  On a fresh restart with the same fast5s, it might run for 3 hours then error.  It has yet to complete without this error on several multi-run sets of fast5s (haven't tried to use `--resume`).  I'm running this as a SLURM job submission.

Command:
`ont-guppy_4.4.1/bin/guppy_basecaller -r -d rerio/basecall_models/ -c res_dna_r941_min_crf_v031.cfg -x 'cuda:0 cuda:1' --num_callers 8 --gpu_runners_per_device 4 --chunks_per_runner 350 --chunk_size 2000 --qscore_filtering --input_path $IN_PATH --save_path $OUT_PATH`

Typical error:
`[guppy/error] pipeline::ThreadedNode::worker_function: Exception thrown in dataHandlerNode worker thread: Sequence contained an unexpected character '>' at position 84
[guppy/error] main: The pipeline has shut down prematurely due to an error condition.
[guppy/warning] main: An error has occurred. Aborting.`

GPU info:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.51.06    Driver Version: 450.51.06    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-PCIE...  On   | 00000000:88:00.0 Off |                    0 |
| N/A   27C    P0    22W / 250W |      0MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-PCIE...  On   | 00000000:89:00.0 Off |                    0 |
| N/A   27C    P0    22W / 250W |      0MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by iiSeymour** [comment]
@RichardCorbett @charles-plessy @drfultz guppy 4.4.2 was just released which fixes this issues - please update https://community.nanoporetech.com/posts/guppy-v4-4-2-patch-release

**Comment by RichardCorbett** [comment]
Running a test with 4.4.2 and already got farther then I would have with 4.4.1.    Might be a day or two before I can confirm complete success.

**Comment by BaylorLyu** [comment]
same issue now happen on guppy_6.0.1, how to aviod this issue?

**Comment by fbrennen** [comment]
Hi @BaylorLyu -- can you provide the full command you're using to call guppy, and the full output that it returns?

**Comment by mehdiborji** [comment]
Hi @fbrennen this is has been happening to me as well, using guppy 6.0.1. It initially happened a few times during rebasecalling of fast5s that were basecalled on mk1c. We moved to off-device basecalling altogether for newer runs this had never happened, until now again.

These are my options:

```
--chunks_per_runner 512 \
--do_read_splitting  \
--disable_qscore_filtering \
-x "cuda:0" --compress_fastq
```

This is the full output:

```
config file:        /home/meb521/ont-guppy/data/dna_r10.4_e8.1_sup.cfg
model file:         /home/meb521/ont-guppy/data/template_r10.4_e8.1_sup.jsn
input path:         /n/scratch3/users/m/meb521/split_4
save path:          /n/scratch3/users/m/meb521/fastq_full_sup_rsplit_nofilt_4
chunk size:         2000
chunks per runner:  512
records per file:   4000
fastq compression:  ON
num basecallers:    4
gpu device:         cuda:0
kernel path:        
runners per device: 12
Found 600 fast5 files to process.
Init time: 4284 ms

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************[guppy/error] pipeline::ThreadedNode::worker_function: Exception thrown in dataHandlerNode worker thread: Basecall telemetry received for non-existent run segment of run ID 47e8d5792c678eb684dd0e881580f57aa4a0e9e4
************************************
[guppy/error] main: The pipeline has shut down prematurely due to an error condition.
[guppy/warning] main: An error has occurred. Aborting.

```

**Comment by fbrennen** [comment]
@mehdiborji that's not a fastq error by the look of it. We've seen this particular issue and are addressing it, but if you've got general guppy bugs I would recommend coming to the Nanopore Community site and posting about them there.

**Comment by Sanaz01** [comment]
I encounter the same issue, after changing the number of options to the guppy_basecaller, I have narrowed down the problem to using these 3 commands together, for my case. 
--bam_out, --trim_barcodes, --trim_adapters

Here is the command that I use - guppy_basecaller -c dna_r9.4.1_450bps_modbases_5hmc_5mc_cg_sup.cfg -i  ./nb3/fast5                      -s basecalled --align_ref ref.fasta --device cuda:0:100% --bam_out --trim_adapters --trim_barcodes --barcode_kits EXP-NBD104 

Here is the error:
![image](https://user-images.githubusercontent.com/46236640/178566315-2125b3d6-70bf-42b7-9c87-c4496941cf9d.png)
