### ISSUE TITLE
Bonito research model, dramatic increase in basecall quality scores

### ISSUE THREAD

**Issue by callumparr** [nanoporetech/rerio#18]
I ran bonito on some old 9.4.1 DNA libraries and the quality scores seems dramatically better and tighter than flip flop model. Is this expected? 

<img width="944" alt="Screen Shot 2021-01-21 at 5 13 38 PM (2)" src="https://user-images.githubusercontent.com/41637575/105323063-07cae600-5c0d-11eb-94ce-5c938dac3fc3.png">
<img width="951" alt="Screen Shot 2021-01-21 at 5 19 44 PM (2)" src="https://user-images.githubusercontent.com/41637575/105323073-0ac5d680-5c0d-11eb-91c2-fc0c1a64a2ef.png">

**Comment by iiSeymour** [comment]
@callumparr looks reasonable - what version of guppy are the flip flop results from and do you have alignment accuracies to compare against?

**Comment by callumparr** [comment]
This was actually an older version from 2019 but I rerun with 4.4.1 and the qualities seem similar. Just looking at accuracies now. 

I did see that bonito consistently gives shorter lengths than flip flop. Is this also expected? Ultimately I want to use better basecalling to help with demultiplexing single-cell RNA seq data sets so ideally want to make sure have the ends are of good quality

**Comment by crysclitheroe** [comment]
Hi, we are installing Guppy, Rerio and bonito basecallers on our gpu cluster, but are wondering how often latest bonito models get updated to Rerio, and where/how we can check this?

Thanks and kind regards
Crystal

**Comment by davidnewman02** [comment]
Closed as this model has now been superseded.
