### ISSUE TITLE
Please help with these issues

### ISSUE THREAD

**Issue by xc611** [nanoporetech/rerio#2]
Hi, 

I downloaded your dataset and tried to use guppy by gpu version: 

gpu/bin/guppy_basecaller --input_path MN21041_FAK63457_354febf2/fast5_pass --fast5_out --save_path guppymb --data_path rerio/basecall_models --config res_rna2_r941_min_flipflop_v001.cfg -x "cuda:0"

I received error:

[guppy/error] main: Layer type 'DeltaSample' has no loading implemented.

Then I tried to use cpu version:

cpu/bin/guppy_basecaller --input_path MN21041_FAK63457_354febf2/fast5_pass --fast5_out --save_path guppymb --data_path rerio/basecall_models --config res_rna2_r941_min_flipflop_v001.cfg

I received error:

terminate called without an active exception
Aborted

Please help, thanks

Jack

**Comment by marcus1487** [comment]
Is this the most recent version of guppy? This looks like an error due to an outdated version of guppy.

**Comment by xc611** [comment]
Thank you so much, I was using guppy 3.4.4 to run, now I download v3.5.2 and it's running!

**Comment by xc611** [comment]
Hi, 

Sorry I have one more question, after I used guppy3.5.2 to call RNA fast5 files with --fast5_out option, and res_rna2_r941_min_flipflop_v001.cfg file, I suppose the base modification information was stored in ModBaseProbs section, but I can't find this table, only Move and Trace table.  Maybe I missed  something here?

Thanks

Jack

**Comment by marcus1487** [comment]
The research RNA model currently included with Rerio does not include any modified bases. See this table https://github.com/nanoporetech/rerio#use-and-description-of-models in the readme which shows any modified bases included in a model. This RNA model is instead intended to improved basecalling accuracy.

**Comment by xc611** [comment]
I see, thank you again. 

Any suggestions for me to call RNA modified bases?

**Comment by marcus1487** [comment]
We are working hard to train RNA modified base basecalling models, but currently don’t have any suitable for release. The current recommendation is to use Tombo with the level sample compare method. This requires an IVT sample for comparison. Without an IVT sample, the Tombo de novo method is available, but is likely to be quite error prone.

**Comment by xc611** [comment]
Thank you very much for the advice.
