### ISSUE TITLE
Methylation (5mC & 6mA) call for MinION R10.3 reads

### ISSUE THREAD

**Issue by yfuruta** [nanoporetech/rerio#20]
Hi,

I am wondering is there any model available for methylation (5mC & 6mA) call for MinION R10.3 reads. Does a config file included in guppy or any model in rerio work? If not, any information about the schedule for publicizing such model?

I just in case tried both dna_r10.3_450bps_fast.cfg and dna_r10.3_450bps_hac.cfg included guppy, but called fast5 didn't include ModBaseProbs table.

For MinION R9.4.1 reads, Megalodon and res_dna_r941_min_modbases-all-context_v001.cfg in rerio worked perfectly!! I'm looking forward to doing same analysis with MinION R10.3 reads.

Thank you so much in advance!

Best,
Yoshi

**Comment by tmassingham-ont** [comment]
Hello.   We don't yet distribute an R10.3 modified base model for Minion and there is no schedule for releasing one.  You may have some success using the Promethion model, recalibrating the methylation calling thresholds according to the instructions in Megalodon.

**Comment by yfuruta** [comment]
Thanks for the information! I will give a try with the Promethion model.

**Comment by davidnewman02** [comment]
5mC and 6mA modification is supported with the latest v10.4.1 chemistry,
