### ISSUE TITLE
Query on base modification

### ISSUE THREAD

**Issue by aswathishiju** [nanoporetech/rerio#22]
HI,
Is it possible to identify base modification caused by deaminated cytosine as Uracil in DNA sequence? 
I one through Megalodon Rerio documentation and found models to identify 5mC and 6mA methylation at motifs, but couldn't see any reference documentation for identification of the Uracil in DNA as a modified base. 
So, is there any base models available to identify Uracil in DNA? 
If not, is it possible to use or modify any of the existing rerio base models for this purpose?

Thanks 
Aswathi

**Comment by marcus1487** [comment]
There is no model currently available for U bases in DNA. We will add this model to the appropriate repos if and when it is available.
