### ISSUE TITLE
mitochondrial dna and models?

### ISSUE THREAD

**Issue by tonperre** [nanoporetech/rerio#23]
Hi,

My knowledge about LRS and ONT is mostly theoretical for now. I read several papers where the config file trained with e. coli underperformed when not using the same species, which makes total sense. I was wondering with was the models from Rerio were trained : a mix of different species, human, mammals? 
My question gets a bit more precise when I'm working with mitochondrial DNA, which has some particularities of the host they're are in and also some bacterial phage, would you recommend any particular model ?

cheers,

**Comment by dithiii** [comment]
I have the same question. I have recently used megalodon to basecall mammalian mitochondrial reads from a 9.4.1 minion run. Most were at 0%, as expected, but overall, the average level was quite a bit higher than with nanopolish. For instance, I got several loci reported as over 70% methylated with megalodon while none were over 35% with nanpolish. I assume this is a training issue.

**Comment by davidnewman02** [comment]
Hi @tonperre,
Apologies for the long delay in replying to this issue! The basecall models are trained using data from a range of species, kingdoms, and domains. We would always recommend using the latest iteration of basecall model and software (currently dorado-v0.5.2 which contains the basecall-model-v4.3.0). 
Please let us know if you want any further guidance on picking the right model for your experiment class.
