### ISSUE TITLE
Different Coverage and % of methylated reads for same site in different models

### ISSUE THREAD

**Issue by dipannita-g** [nanoporetech/rerio#24]
Hi!

So I tried to run my fast5 dataset in Megalodon using two different models for 6mA calling.

dna_r9.4.1_450bps_modbases_dam-dcm-cpg_hac.cfg
res_dna_r941_min_modbases-all-context_v001.cfg

For the same site, I see different coverage and %of methylated reads in respective BED file outputs. Can you explain why is this happening? I am kind of new to seq data analysis and this is confusing me a bit. 

Thanks!

**Comment by davidnewman02** [comment]
We now recommend Dorado for most modbase calling. Could you please try there and raise a new issue if the problem persists?
