### ISSUE TITLE
bonito models not working with `--barcode_kits`

### ISSUE THREAD

**Issue by xlin-1** [nanoporetech/rerio#26]
Hi,

I got an error message when I tried to run the basecaller with demultiplex argument:

[guppy/error] main: Error: The following barcoding kits are not supported (EXP-NBD104).
[guppy/warning] main: An error has occurred. Aborting.

I was using guppy v4.4.2 with bonito model res_dna_r941_min_crf_v032.cfg. Basecaller worked fine without `--barcode_kits` flag.

**Comment by tmassingham-ont** [comment]
Hello.  Thanks for reporting, I think this is most likely an error with Guppy and I've passed your bug report to the relevant team.

**Comment by marcus1487** [comment]
See instruction in the README for barcode support.
