### ISSUE TITLE
Are 5mC and 5hmC distinguished in res_dna_r941_min_modbases_5mC_5hmC_v001.cfg?

### ISSUE THREAD

**Issue by Shians** [nanoporetech/rerio#28]
I'm still not too familiar with the wealth of options in Megalodon, but from what I understand, the modification would be specified by `m CG 0`, which is the motif and location for both 5mC and 5hmC. So is there a way to distinguish them in the output?

**Comment by marcus1487** [comment]
The `m` stands for 5mC. `h` stands for 5hmC. To call both from megalodon you can use `--mod-motif mh CG 0`. But I would highly recommend using the updated Remora models for this task. The accuracy should be much higher than the flip-flop models currently released with rerio.

**Comment by marcus1487** [comment]
A table of single letter codes for modified bases can be found in the SAM file spec here: https://samtools.github.io/hts-specs/SAMtags.pdf
