### ISSUE TITLE
Guppy_Basecaller 5.0.11 - GlobalNormTransducer layer has non-zero stay state weight! - Error

### ISSUE THREAD

**Issue by ziejan** [nanoporetech/rerio#29]
Hi,

when we try to gpu-basecall our reads with guppy version 5.0.11 and the config file "res_dna_r941_min_crf_v031.cfg" we get the following error message:

ONT Guppy basecalling software version 5.0.11+2b6dbffa5
config file:        /opt/ont/guppy/data/res_dna_r941_min_crf_v031.cfg
model file:         /opt/ont/guppy/data/res_dna_r941_min_crf_v031.jsn
input path:         input_Data/
save path:         save_Path/
chunk size:         720
chunks per runner:  320
minimum qscore:     10
records per file:   0
num basecallers:    4
gpu device:         cuda:0
kernel path:
runners per device: 8

[guppy/error] main: GlobalNormTransducer layer has non-zero stay state weight!
[guppy/warning] main: An error has occurred. Aborting.

We saw that the config isnt tested with this guppy version but we would really like to continue using this config file since we get much better Q-scores with it.

Any suggestions are appreciated

**Comment by tmassingham-ont** [comment]
Hello.  Unfortunately the v031 CRF models are not compatible with Guppy version >= 5.0, please try an earlier version.

**Comment by iiSeymour** [comment]
@ziejan all the DNA models in Guppy 5 are now CRF style models and replace the models here in rerio.  `dna_r9.4.1_450bps_sup.cfg` is the config you will want and should have comparable q-scores.

**Comment by ziejan** [comment]
Hey,

Thx for your replies. I used dna_r9.4.1_450bps_**hac**.cfg for our last run but got a Q-Score of only ~10. With res_dna_r941_min_crf_v031.cfg I usually got something aroung 13-15.

I will try dna_r9.4.1_450bps_**sup**.cfg next time.
Thanks!
