### ISSUE TITLE
low qscores

### ISSUE THREAD

**Issue by jagos01** [nanoporetech/rerio#3]
Hello,
I would like to compare the research models (res_dna_r941_min_modbases-all-context_v001.cfg, res_dna_r941_min_flipflop_v001.cfg and res_dna_r941_min_rle_v001.cfg) with data previously called with guppy v.3.4.4.  
I am using guppy v3.5.2 with the research models to basecall multi-fast5 files. When I basecall with the flipflop or rle models most of my reads have qscore < 7.  However, when basecalling with the modbases-all-context model, most reads have a qscore > 7 (similar numbers to guppy v3.4.4).  Is this because the qscores are not calibrated or is there another reason for the low qscores?
Thanks,
Scott

**Comment by marcus1487** [comment]
This is indeed because the q-scores are not calibrated in the research models included in rerio.

**Comment by jagos01** [comment]
Thanks

**Comment by callumparr** [comment]
I only noticed this for the RLE model included for DNA but if I use the fliflop research model for DNA the q-scores seem similar to the production guppy models.

**Comment by tmassingham-ont** [comment]
While not identical, the research and production flip-flop models (Guppy 3.5 onwards) will be very similar and I suspect the default calibration transfers quite well.  The RLE models have a very different structure and the (uncalibrated) quality scores produced should not be relied upon.
