### ISSUE TITLE
res_dna_r941_min_modbases_5mC_5hmC_v001.cfg

### ISSUE THREAD

**Issue by jennyg86** [nanoporetech/rerio#31]
Hi,

On which experiment/database the `res_dna_r941_min_modbases_5mC_5hmC_v001.cfg` is based on?

Thank you!

**Comment by marcus1487** [comment]
Yes, `res_dna_r941_min_modbases_5mC_5hmC_v001` should identify 5hmC and 5mC in CpG contexts as well as the `res_dna_r941_min_modbases_5mC_5hmC_CpG_v001` model. This is why `res_dna_r941_min_modbases_5mC_5hmC_CpG_v001` was dropped from the table in the Rerio README. Only the models in the main page are suggested for use. Other models remain in the repository to allow access for projects that used these models previously.

We are working on releasing the training procedure for these and other models, but do not have this material together at this time. The models released in Rerio are considered research/experimental models and thus have not been validated to the same extent as the models found in the Guppy production basecaller.

**Comment by TerrenceT-79** [comment]
@marcus1487 I have some repeat sequence that I would like to get methylation calls over. The repeats are GGCCGG the internal CpG in this sequence actually miscalls at one of the CpG positions nearly every time in both the fw and rev strands. I am able to get some methylation calls where the correct basecalls are made but the incorrect T and A calls make it difficult to interpret the data. this is with the res_dna_r941_min_modbases_5mC_CpG_v001.cfg model.
thanks

<img width="1424" alt="Screen Shot 2022-04-14 at 11 54 20 PM" src="https://user-images.githubusercontent.com/25189612/163515674-ccad43b1-8d97-483f-9eed-8ed6e347e2ac.png">
.
