### ISSUE TITLE
Error initialising basecall server

### ISSUE THREAD

**Issue by dipannita-g** [nanoporetech/rerio#32]
Hi Marcus!

I have ran Megalodon successfully multiple times by now for my analysis until a month ago. But now when I try to run it, I get guppy initialisation failure. Even after fresh reinstallation of Guppy and Megalodon, I get the same error. I have even downloaded Rerio models fresh but the problem still persists. Here is the error that I am getting:

`Could not load barcoding parameter file './rerio/basecall_models/read_splitting/read_splitting.cfg'.. Error initialising basecall server using port: ipc://auto. Aborting.
`

I don't see this /read_splitting/read_splitting.cfg in my rerio directory either in the new or old download. I don't know where will I get this config file. I think this error has started cropping up after I updated ont-guppy recently.

I will really appreciate any help regarding this! 

Thank you
Dipannita

**Comment by marcus1487** [comment]
This is an issue with rerio compatibility with guppy6. A patch has been applied in github. Updating your rerio repository (`git pull` from rerio root) should resolve this issue.

**Comment by dipannita-g** [comment]
It works now. Thank you for the help!

**Comment by Fatihlrcfs** [comment]
hi all 

I am getting the same error. (Could not load barcoding parameter file '/cluster/lrcfs/2397405/bin/rerio/basecall_models/read_splitting/read_splitting). Could you give more explanation how did you solve/do more clearly? ı am new in this field sorry about that. many thanks.

**Comment by dipannita-g** [comment]
Hi @Fatihlrcfs 

My problem was a compatibility issue of the older version of the Rerio repository with the new Guppy update. If you had downloaded the Reio repository before Marcus applied the patch (check the date of the above comments), you will get this error if you try running it with the latest Guppy version.

Have you tried downloading the Rerio repository afresh? If not, do should do it and see if that helps. It worked in my case.

**Comment by Fatihlrcfs** [comment]
Hi @dipannita-g 
I just deleted the previous repository and downloaded it again with the same installation. And it looks like it is working now. thanks for your response.
