### ISSUE TITLE
request clair3 model for r941_e8_hac_g507

### ISSUE THREAD

**Issue by nextgenusfs** [nanoporetech/rerio#33]
Would it be possible to also get a general model for variant detection using Clair3 for the current "Q-line" R9.4.1 and the HAC_g507 model?  Thanks.

**Comment by cjw85** [comment]
Hi Jon,

I think @aquaskyline has these.

https://github.com/HKU-BAL/Clair3/blob/main/docs/guppy5.md

Rerio contains only additional models for newer chemistries.

**Comment by nextgenusfs** [comment]
Okay thanks for the pointer!
