### ISSUE TITLE
Downloading models fails with  "[Errno 61] Connection refused"

### ISSUE THREAD

**Issue by ppapasaikas** [nanoporetech/rerio#39]
Hello,

I am trying to download some of the latest rerio models using the download_model.py script.
Either when attempting to download individual models or without specifying them I get an error:
`Downloading model_name_YYYY
Error for mode_name_lYYY (<urlopen error [Errno 61] Connection refused>)
`
Any help on the issue would be much appreciated.

**Comment by davidnewman02** [comment]
Hi @ppapasaikas,

Apologies for the delay in replying; are you still having issues with model download?
`Errno 61` indicates that you are unable to connect to the server to start the model download, please check your firewall settings to ensure you are able to make the connection.
