### ISSUE TITLE
Error when downloading clair3 models via rerio "(not a gzip file)"

### ISSUE THREAD

**Issue by IraDeveson** [nanoporetech/rerio#41]
Hi there, I'm attempting to download the clair3 variant calling models via rerio but I have hit the following error:

```
./rerio/download_model.py --clair3

Models to download
  1: r104_e81_hac_g5015
  2: r104_e81_sup_g5015
Downloading r104_e81_hac_g5015
Error for r104_e81_hac_g5015 (not a gzip file)
Downloading r104_e81_sup_g5015
Error for r104_e81_sup_g5015 (not a gzip file)

```

I don't get a similar error when if I download basecall models; it's only affecting the clair3 download.

Thanks for your help

**Comment by ftostevin-ont** [comment]
The download links for the clair3 models should now be fixed.

**Comment by IraDeveson** [comment]
This works fine now - thank you for addressing the issue :)
