### ISSUE TITLE
unexpected model download behaviour (5mC_all_context_sup_r1041_e82)

### ISSUE THREAD

**Issue by QGouil** [nanoporetech/rerio#42]
Hi Marcus,

just a small issue.
`python3 download_model.py remora_models/5mC_all_context_sup_r1041_e82`

only downloads a text file, "5mC_all_context_sup_r1041_e82", that contains the link to the tgz archive. But wget and tar xzf on this are a workaround.
Cheers,

Quentin

**Comment by ftostevin-ont** [comment]
Hi Quentin,
You need to add the `--remora` flag to download remora models; i.e. 
```python3 download_model.py --remora remora_models/5mC_all_context_sup_r1041_e82```

The text file that is part of the rerio repo that tells the download script the url from which to get the model.
Best,
Filipe
