### ISSUE TITLE
Running 5mc_all_context remora model on Megalodon

### ISSUE THREAD

**Issue by jcolicchio-soundag** [nanoporetech/rerio#43]
We are interested in trying out doing methylation calling on data generated from an R10.4.1 flow cell that has already been basecalled using the SUP basecalling model.  

From everything we've read, it seems like this is the exact use for the Rerio model: 5mC_all_context_sup_r1041_e82

I had a few questions about the logistics of actually running this model though.  We have successfully downloaded the file and have the .onnx, but im not sure of what we should be using for the following parameters:

1)  Should we use the --do-not-use-guppy-server command if we want to use the basecalling that has already been done and is in our fast5 files?

2) If not, what should we specify for our --guppy-config file?  My intuition is: dna_r10.4.1_e8.2_260bps_sup.cfg, but when we try this it times out without ever starting. When looking at the logs: "Could not load guppy server configuration state: 'Configurations'" 

3) For this rerio model, should we specify --remora-modified-bases?

If this is of any help, here is basically what we are trying, that is working is:

megalodon /SSD/TestData/fast5_pass/ --reference testref.mmi --devices 0 --guppy-server-path /opt/ont/guppy/bin/basecall_server --outputs mod_mappings mods mappings --output-directory /SSD/test_directory/ --processes 30 --remora-model  /opt/ont/guppy/data/remora_models_5mc_all_context_sup_r1041_e82.onnx  --guppy-config dna_r10.3_450bps_hac.cfg

It seems to be running, but i am not sure if it appropriate, in particular the guppy-config file. 

Thanks in advance

**Comment by marcus1487** [comment]
At this time we do not have a way to run Remora modified base calling after basecalling has completed. This functionality will be added in the next release of Remora along with a number of other changes. Megalodon does not and will not support this functionality.

In the next release of Remora a command `remora infer from_pod5_and_bam` will be added. Note that this command will require the basecalls to include the move table (the link between the basecalls and the signal).
