### ISSUE TITLE
5mC_all_context_sup_r1041_e82 will there be a version for pore r9.4.1 for DNA methylation inference in all contexts?

### ISSUE THREAD

**Issue by AlineMuyle** [nanoporetech/rerio#46]
Hi, I am using Bonito to run DNA methylation inference in all contexts and wondering whether you plan to release the model equivalent to 5mC_all_context_sup_r1041_e82 but for pore r9.4.1?
It would be really useful because the old model res_dna_r941_min_modbases-all-context_v001 is not up to date.
Thank you for your help.

**Comment by marcus1487** [comment]
Unfortunately there are no plans currently to release a new Remora all-contexts 5mC model for R9.4.1. The samples to train this model take quite a bit of effort so we will be supporting kit14 with updates at this time.
