### ISSUE TITLE
Remora models

### ISSUE THREAD

**Issue by CWYuan08** [nanoporetech/rerio#48]
Hi after downloading the remora model, there seem to be only 5mC_all_context_sup_r1041_e82, does it only work for 5mC (not 5hmC and only for super accurate reads?
are there newer Remora modified basecalling models? where to download them?

Many thanks!

Best,
CW

**Comment by marcus1487** [comment]
I would recommend the newer dorado all-context models which were released recently. The corresponding Remora models can also be found in the Remora repository.

These modified base callers are linked to the super accurate basecallers for now. We are in active development to explore application of all-context modified base calling to HAC basecallers.

The current offering includes 5mC and 6mA models. We are working towards an all-context 5hmC model as well, but this is not currently available.
