### ISSUE TITLE
res_dna_r941_min_flipflop_v001.cfg

### ISSUE THREAD

**Issue by callumparr** [nanoporetech/rerio#5]
Is the research model attached to this config, res_dna_r941_min_flipflop_v001.cfg, the same model used in production guppy? 

I was recently testing accuracy for subset of minion DNA reads (not native) with guppy 3.6.0 and older version, and then to models in rerio including this flipflop model and the RLE model.

**Comment by tmassingham-ont** [comment]
The model is not identical to that in Guppy:  the structure and method of training are the same, but the production models are trained separately and so there will be slight differences in parameters and overall performance.  
The Rerio models provide an idea of where base calling is going, but have not gone through a lengthy validation and are not ready for general use.  Some of the models will eventually appear in the production base caller, after retraining and validation.  In the case of the new flip-flop models, this happened quite rapidly.
