### ISSUE TITLE
Dorado models downloading script not working

### ISSUE THREAD

**Issue by AlexanRNA** [nanoporetech/rerio#50]
Hello, 

I have tried downloading your new Dorado models using the `python3 download_model.py --dorado` command as specified in your README, however, this command doesn't work . 
The script only works if I precise which model and include `_url` at the end, for instance `python3 download_model.py --dorado dorado_models/res_dna_r10.4.1_e8.2_400bps_sup@v4.0.1_5mC@v2_url
` .  

Cheers,

Alex

**Comment by pwh124** [comment]
Ran into this myself... it's not entirely clear based on the README, but you have to run _**both**_ steps listed:

```
python3 download_model.py --dorado
python3 download_model.py --dorado dorado_models/res_dna_r10.4.1_e8.2_400bps_sup@v4.0.1*
```
The model files needed should download and be in the same directory at the *_url files.

**Comment by marcus1487** [comment]
I just pushed a small fix that allows either command in docs to work now. Please re-open if further issues are encountered.
