### ISSUE TITLE
Clair3 Model Compatibility

### ISSUE THREAD

**Issue by keremozdel** [nanoporetech/rerio#51]
Hello,

I'm using Clair3 for variant calling on human samples that were sequenced using R10 flowcells. When I used the `r941_prom_sup_g5014` model, developed by Clair3 developers, I obtained variants with high depth that appear to be significant according to ClinVar. However, upon switching to the `r1041_e82_400bps_hac_g632` model, I could no longer detect these variants. Firstly, I would like to ask whether it is appropriate to use older models for new chemistry. Additionally, I'm curious whether I should consider these variants as false positives.

I am using Guppy v6.5.7 for basecalling.

Thank you in advance!

**Comment by natashaberthold** [comment]
I've been wondering a similar thing- I have been using dorado for basecalling and ran my sequencing on R9.4.1 flow cells with kit 10 chemistry. Currently all the dorado models appear to be for R10.4.1, and vice versa with all the models for R9.4.1 being Guppy models. I'm new to all this bioinformatics and am wondering if the model you use has to match the model you basecalled with?

**Comment by keremozdel** [comment]
Hi @nbertholdpgc ,
I'm not sure if this information helps, but I performed variant calling on the same samples using both the `r941_prom_sup_g5014` and `r1041_e82_400bps_sup_v420` models. Even though the samples were sequenced using R10 flowcells, I observed a significant decrease in recall when using the dorado model. Additionally, I was unable to obtain specific variants that were validated by Illumina reads. To answer your question, I believe it's important to use the matching model to achieve more accurate results.

**Comment by ftostevin-ont** [comment]
It is recommended to use the matched model for the basecaller to get the best variant calling results.

However, it has been reported that the r10.4.1 models can occasionally fail to call snps in high-depth datasets, and that downsampling reads to ~60X coverage can recover these calls. @keremozdel If you have high-depth data, then this is probably why you see variant calls from the r9.4.1 model (that does not show this behaviour) that are not called by the r10.4.1 model. It's likely that you will see better results using the r10.4.1 model with a lower-depth subsample of reads than the r9 model with a higher depth (Clair3 in any case internally downsamples to ~90X maximum coverage).

@nbertholdpgc If you have r9.4.1 data then you should use the clair3 models provided by the Clair3 developers, regardless of whether this was basecalled with guppy or dorado. The same r9.4.1 basecaller models are used by both guppy and dorado.

**Comment by davidnewman02** [comment]
Hello @keremozdel @nbertholdpgc,

We have now updated the clair3 models for both v4.2 and v4.3 to handle data at higher depths, if you'd like to (re)download the latest models then this issue should now be fixed.

**Comment by mproberts99** [comment]
Hi, I was just curious how it is able to handle the higher depths now. Does that mean it was trained at 89x instead of 60x like the guppy R10 model? Asking because we currently downsample to 60x with the guppy R10 SUP model and are moving over to Dorado so I was curious if we need to keep our downsampling step.
