### ISSUE TITLE
bacterial methylation model

### ISSUE THREAD

**Issue by asershova** [nanoporetech/rerio#52]
Dear Authors,

I run dorado with bacterial methylation model from the rerio, res_dna_r10.4.1_e8.2_400bps_sup@2023-09-22_bacterial-methylation
My command is:
dorado basecaller dna_r10.4.1_e8.2_400bps_sup@v4.2.0 pod5_dir --modified-bases-models rerio/dorado_models/res_dna_r10.4.1_e8.2_400bps_sup@2023-09-22_bacterial-methylation --emit-moves --reference genome.fna > out.bam

I got an error message

[2023-10-12 07:51:09.414] [error] [error] key "general" not found in the top-level table
 --> res_dna_r10.4.1_e8.2_400bps_sup@2023-09-22_bacterial-methylation/config.toml
   |
 1 | [model]
   | ^--- the top-level table starts here

I would appreciate any advice on how to solve it.

Best regards,

Anna

**Comment by ftostevin-ont** [comment]
The model `res_dna_r10.4.1_e8.2_400bps_sup@2023-09-22_bacterial-methylation` is a canonical basecalling model, not a modified bases model. In your command line it should replace `dna_r10.4.1_e8.2_400bps_sup@v4.2.0`. The new model produces more accurate basecalls in a range of bacterial methylation motifs but does not specifically identify methylation sites, for that you should still use the existing methylation models.

**Comment by asershova** [comment]
Great, thank you!
