### ISSUE TITLE
Clair3 v420 on v4.3.0

### ISSUE THREAD

**Issue by pustoshilov-d** [nanoporetech/rerio#53]
Hello, I just want to clarify.
How normal and compatible is it to use Clair3 model r1041_e82_400bps_sup_v420 to process data from Dorado dna_r10.4.1_e8.2_400bps_sup@v4.3.0 or should I wait for v430? 
If so, when approximately to expect it?

**Comment by davidnewman02** [comment]
Hi @pustoshilov-d 

Clair3 models to match with v4.3-basecalls have been released this morning.

Thanks,
David
