### ISSUE TITLE
remora model 5mC all context 1041 E82 support for 260bp?

### ISSUE THREAD

**Issue by BjoernUsadel** [nanoporetech/rerio#54]
Hi 
I am just trying to methylation call some older data,
Does the [5mC_all_context_sup_r1041_e82](https://github.com/nanoporetech/rerio/blob/master/remora_models/5mC_all_context_sup_r1041_e82) model support 260bp and 400bp speeds or just one of them? 

Thanks
Björn

**Comment by davidnewman02** [comment]
There are updated 5mC all context models available for the 400bps condition available in Dorado, which uses Remora as a backend for methylation detection. Unfortunately 5mC-all-context is not officially supported for the 260bps condition.
