### ISSUE TITLE
v4.3.0 models and bacterial methylation model

### ISSUE THREAD

**Issue by mbhall88** [nanoporetech/rerio#57]
I believe the bacterial methylation-aware model was released before the v4.3.0 dorado models, which provide a big boost in accuracy. Are the v4.3.0 models methylation-aware, or is the methylation-aware model still going to be an improvement over the v4.3.0 models?

**Comment by davidnewman02** [comment]
Hi @mbhall88,
The improvements to bacterial methylation calling made in the initial release have now been integrated into the mainline models. We recommend using the latest v4.3.0 models for all basecalling including bacterial methylation calling. 
David
