### ISSUE TITLE
Urgent Help Required: Regarding Error for modified basecalling

### ISSUE THREAD

**Issue by PRIYANKA-22091995** [nanoporetech/rerio#58]
I was trying to run the following command for modified basecalling:
guppy_basecaller -i /DATA/BioLab/Priyanka/FAST5/EB_EL_FAST5/fast5/ -s /DATA/BioLab/Priyanka/FAST5/ -c /home/arnav/workspace/rerio/basecall_models/res_dna_r941_min_modbases-all-context_v001.cfg --recursive -a /home/arnav/workspace/PlasmoDB-61_PvivaxSal1_Genome.fasta --bam_out -x cuda:0 -m /home/arnav/workspace/rerio/basecall_models/res_dna_r941_min_modbases-all-context_v001.jsn --barcode_kits EXP-NBD104

But got the below error.
<img width="943" alt="guppy error" src="https://github.com/nanoporetech/rerio/assets/109784286/d2916d20-f232-439d-bd24-20b310dd5392">

**Comment by davidnewman02** [comment]
Hi @PRIYANKA-22091995,

It looks like you're using guppy-v6.3.2 here, however this model lists compatibility with guppy-v3.5.1 ([README](https://github.com/nanoporetech/rerio/blob/master/basecall_models/README.rst)) and it seems like this is causing an issue with model loading. Are you able to retry with an older guppy version?
