### ISSUE TITLE
Risks involved when running a model tested on dorado v0.4.3 on v.0.5.3?

### ISSUE THREAD

**Issue by Ge0rges** [nanoporetech/rerio#59]
Hello,

I was wondering if there significant changes or issues known that would affect the results when using a rerio model tested on dora v0.4.3 with v0.5.3. Thank you.

**Comment by davidnewman02** [comment]
Hi @Ge0rges,
The results of basecalling using Dorado v0.4.3 and v0.5.3 should be almost identical for a given model, we attempt to ensure backwards compatibility between dorado versions. The majority of changes between these versions are minor-fixes and additional features, so should not affect the output with existing models.

We recommend using the latest models in Dorado whenever possible as these are likely to give the best results, unless you have a very specific application which is currently only experimentally supported.
David
