### ISSUE TITLE
can't download models

### ISSUE THREAD

**Issue by michieitel** [nanoporetech/rerio#6]
Hi!

I was trying to download the recent models after pulling the latest rerio version. After loading the repo I was running
`python3 download_model.py` (using python v. 3.7.6) and got the following error message:

>   File "download_model.py", line 66
>     except as e:
>             ^
> SyntaxError: invalid syntax

What might have gone wrong here?

thanks
Michael

**Comment by tmassingham-ont** [comment]
Our fault, sorry.  Now fixed.
