### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by angelluigi** [nanoporetech/rerio#60]
HI,

Im trying executing this code. But i have received this problem.

megalodon  fast5_pass/ --guppy-server-path ./ont-guppy/bin/guppy_basecall_server --guppy-params "-d ./rerio/basecall_models/" --guppy-config res_dna_r941_min_modbases_5mC_v001.cfg --processes 40 --overwrite
[15:56:06] Running Megalodon version 2.5.0
[15:56:06] Loading guppy basecalling backend
Segmentation fault

Thanks

**Comment by davidnewman02** [comment]
Hi @angelluigi,

The Megalodon project has now been replaced by Dorado (which includes Remora modified basecalling as a dependency). If you are still having issues with these tools please raise an issue on the relevant repository. 

Thanks,
David
