### ISSUE TITLE
Regarding m6A modified Basecalling

### ISSUE THREAD

**Issue by PRIYANKA-22091995** [nanoporetech/rerio#62]
Hi,

I was trying to do m6A modified basecalling of data generated from R9 flowcell by using trained RNN model i.e. res_dna_r941_min_modbases-all-context_v001 by using guppy v3.5.1.
But, unfortunately, I was unable to do modified basecalling. The basecalling was completed, but unfortunately the bam file generated after minimap2 was without any modifications. It would be nice to have your insights on the same or is there a alternative way to do modified basecalling for m6A.

**Comment by marcus1487** [comment]
Could you post the exact commands you have used?
