### ISSUE TITLE
Compatibilities Clair3 / Dorado model

### ISSUE THREAD

**Issue by Lipinski-B** [nanoporetech/rerio#64]
Hello,

I have few question related to the compatibility between Clair3 model and Dorado model.

_ I would like to know what could be the differences on my variant calling if I switch Clair3's model from **_r1041_e82_400bps_sup_v430_** to **_r1041_e82_400bps_sup_v500_**, considering that I can only use Dorado model dna_r10.4.1_e8.2_400bps_sup@v4.3.0 ?

_ I saw that **_r1041_e82_400bps_sup_v430_** Clair3's model was deprecated, can you tell us why exaclty? Considering that **_r1041_e82_400bps_sup_v410_** is not deprecated, does it mean that **_r1041_e82_400bps_sup_v410_** is still ok to use but not **_r1041_e82_400bps_sup_v430_**  with Dorado model dna_r10.4.1_e8.2_400bps_sup@v4.3.0 ?

_ Knowing that **_r1041_e82_400bps_sup_v430_** is deprecated, is that better to use **_r1041_e82_400bps_sup_v410_** or **_r1041_e82_400bps_sup_v500_** Clair3's model with Dorado model dna_r10.4.1_e8.2_400bps_sup@v4.3.0 ?

Many thanks in advance for your answer.
Best regards,
Boris

**Comment by davidnewman02** [comment]
Hi @Lipinski-B,

In general we recommend using the clair3-model version associated with the dorado-basecall model version, so if you have basecalled with `dna_r10.4.1_e8.2_400bps_sup@v4.3.0` in Dorado then you should pair this with the `r1041_e82_400bps_sup_v430` clair3 model.

The reason we list the v430 model as "deprecated" is that we recommend using the latest basecall+clair3 model appropriate for your data-type (r10.4.1-400bps) to get the best results. The older models which are listed as "latest" are the latest for their condition (e.g. v4.1.0 for the r10.4.1-260bps condition). Apologies for the confusion here, we'll look at updating the documentation to make it more clear in future. 

Thanks,
David
