### ISSUE TITLE
5hmC for PromethION?

### ISSUE THREAD

**Issue by wdecoster** [nanoporetech/rerio#7]
Hi,

Is a model for 5mC and 5hmC (CpG context) calling for PromethION planned or possible to make?

Thanks,
Wouter

**Comment by marcus1487** [comment]
There is no current plan/timeline to train/release this model. The process to create training datasets for 5hmC models is more of a research release than other models. We are working to improve this process and make it more reproducible to hopefully get models trained over a larger spectrum of the available devices and/or pore types, but do not have a firm timetable for this at this time.

**Comment by wdecoster** [comment]
Oh, okay, unfortunate. And it probably wouldn't really make sense to use the minion 5hmC model?

**Comment by marcus1487** [comment]
I have not tested this at this time. There is a chance there would be some signal when using the minion model on promethion data, but we have not looked at this internally at this time.

**Comment by davidnewman02** [comment]
5hmC methylation calling is now supported in Dorado
