### ISSUE TITLE
Question: Model for R10 flow cell and (meta)transcriptomics

### ISSUE THREAD

**Issue by VGalata** [nanoporetech/rerio#8]
Hello,

We wanted to use the R10 flow cells for metagenomics and metatranscriptomics analysis. Does one need a dedicated model file for the transcriptomics data?

Thank you very much in advance!

Best,
Valentina

**Comment by susheelbhanu** [comment]
Hi @tmassingham-ont , 

I'm wondering the same thing because we are interested in running transcriptomics using the R10 flowcells, but did not find the respective model for this purpose. 

Thank you for your help!
-Susheel

**Comment by marcus1487** [comment]
If the transcriptomics data is cDNA, then the released R10 model is applicable. I don't believe direct RNA on R10 flowcells is currently supported.

**Comment by VGalata** [comment]
Dear @marcus1487, thank you very much!
